<template>
<div class="wrapper-code main">
    <div class="numbers">
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">3</span>
        <span class="line">3</span>
        <span class="line">3</span>
        <span class="line">3</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
        <span class="line">2</span>
    </div>
    <div class="wrapper" onscroll="document.getElementsByClassName('numbers')[0].scrollTop = this.scrollTop;">
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
        <span class="line">#include &lt;stddef.h&gt;</span>
    </div>
</div>
</template>
